/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.95
 * Generated at: 2024-10-01 15:18:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class deleteContact_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/E:/projects/java/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/java_project/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1727693938867L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"UTF-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("  <title>Contact Us</title>\r\n");
      out.write("  <style>\r\n");
      out.write("    * {\r\n");
      out.write("      margin: 0;\r\n");
      out.write("      padding: 0;\r\n");
      out.write("      box-sizing: border-box;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    body, html {\r\n");
      out.write("      height: 100%;\r\n");
      out.write("      font-family: 'Arial', sans-serif;\r\n");
      out.write("      background-image: url('back.jpg'); /* Background image */\r\n");
      out.write("      background-size: cover;\r\n");
      out.write("      background-position: center;\r\n");
      out.write("      background-repeat: no-repeat;\r\n");
      out.write("      display: flex; /* Center content */\r\n");
      out.write("      justify-content: center;\r\n");
      out.write("      align-items: center;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .container {\r\n");
      out.write("      max-width: 800px;\r\n");
      out.write("      margin: 50px auto;\r\n");
      out.write("      background: rgba(255, 255, 255, 0.9); /* Slightly transparent white background */\r\n");
      out.write("      padding: 30px;\r\n");
      out.write("      box-shadow: 0 0 15px rgba(0, 0, 0, 0.1);\r\n");
      out.write("      border-radius: 10px;\r\n");
      out.write("      overflow-y: auto;\r\n");
      out.write("      max-height: 90vh;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    h2 {\r\n");
      out.write("      margin-bottom: 20px;\r\n");
      out.write("      color: #333;\r\n");
      out.write("      text-align: center;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .nav-menu {\r\n");
      out.write("      background: #28a745; /* Green background for the menu */\r\n");
      out.write("      padding: 15px;\r\n");
      out.write("      border-radius: 5px;\r\n");
      out.write("      margin-bottom: 30px;\r\n");
      out.write("      text-align: center;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .nav-menu a {\r\n");
      out.write("      color: white;\r\n");
      out.write("      text-decoration: none;\r\n");
      out.write("      margin: 0 15px;\r\n");
      out.write("      font-size: 16px;\r\n");
      out.write("      transition: color 0.3s;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .nav-menu a:hover {\r\n");
      out.write("      text-decoration: underline;\r\n");
      out.write("      color: #d4edda; /* Lighten on hover */\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .form-wrapper {\r\n");
      out.write("      background-color: rgba(255, 255, 255, 0.8); /* Slightly transparent white background for the form */\r\n");
      out.write("      padding: 50px 40px;\r\n");
      out.write("      box-shadow: rgba(0, 0, 0, 0.05) 0px 4px 20px 7px;\r\n");
      out.write("      border-radius: 6px;\r\n");
      out.write("      text-align: center;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .input, .textinput {\r\n");
      out.write("      width: 100%;\r\n");
      out.write("      padding: 15px;\r\n");
      out.write("      border: 2px solid #007bff; /* Match the theme */\r\n");
      out.write("      font-size: 16px;\r\n");
      out.write("      color: black;\r\n");
      out.write("      border-radius: 4px;\r\n");
      out.write("      margin-bottom: 20px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .textinput {\r\n");
      out.write("      min-height: 150px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .submit-btn {\r\n");
      out.write("      width: 100%;\r\n");
      out.write("      background-color: #f44336; /* Red color for delete */\r\n");
      out.write("      height: 60px;\r\n");
      out.write("      font-size: 20px;\r\n");
      out.write("      font-weight: 700;\r\n");
      out.write("      color: white;\r\n");
      out.write("      border: none;\r\n");
      out.write("      border-radius: 4px;\r\n");
      out.write("      cursor: pointer;\r\n");
      out.write("      transition: background 0.3s;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .submit-btn:hover {\r\n");
      out.write("      background-color: #c62828; /* Darker red on hover */\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .social-media-links {\r\n");
      out.write("      display: flex;\r\n");
      out.write("      justify-content: space-evenly;\r\n");
      out.write("      margin: 50px 0;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .link-img {\r\n");
      out.write("      width: 30px;\r\n");
      out.write("      height: 30px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    ::placeholder {\r\n");
      out.write("      color: #dadada;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    @media (max-width: 768px) {\r\n");
      out.write("      .input, .textinput, .submit-btn {\r\n");
      out.write("        width: 100%;\r\n");
      out.write("      }\r\n");
      out.write("    }\r\n");
      out.write("  </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("  ");

    String Id = request.getParameter("id");
    String Name = request.getParameter("name");
    String Email = request.getParameter("email");
    String Phone = request.getParameter("phone");
    String Msg = request.getParameter("msg");
  
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <div class=\"container\">\r\n");
      out.write("    <div class=\"nav-menu\">\r\n");
      out.write("       <a href=\"#\">Dashboard</a>\r\n");
      out.write("       <a href=\"userAccount.jsp\">My Account</a>\r\n");
      out.write("       <a href=\"contactUs.jsp\">Contact Us</a>\r\n");
      out.write("       <a href=\"contactInsert\">MyInquries</a>\r\n");
      out.write("     </div>\r\n");
      out.write("\r\n");
      out.write("    <h2>Get in Touch</h2>\r\n");
      out.write("\r\n");
      out.write("    <form action=\"contactDelete\" method=\"post\" class=\"form-wrapper\">\r\n");
      out.write("      <input class=\"input\" name=\"id\" placeholder=\"User ID\" value=\"");
      out.print( Id );
      out.write("\" readonly>\r\n");
      out.write("      <input class=\"input\" name=\"UserName\" placeholder=\"Name\" value=\"");
      out.print( Name );
      out.write("\" readonly>\r\n");
      out.write("      <input class=\"input\" name=\"Email\" placeholder=\"Email\" value=\"");
      out.print( Email );
      out.write("\" readonly>\r\n");
      out.write("      <input class=\"input\" name=\"PhoneNumber\" placeholder=\"Phone Number\" value=\"");
      out.print( Phone );
      out.write("\" readonly>\r\n");
      out.write("      <textarea class=\"textinput\" name=\"Msg\" placeholder=\"Message\" readonly>");
      out.print( Msg );
      out.write("</textarea>\r\n");
      out.write("      <button type=\"submit\" class=\"submit-btn\">Delete</button>\r\n");
      out.write("    </form>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"social-media-links\">\r\n");
      out.write("      <a href=\"#\"><img class=\"link-img\" src=\"https://workik-widget-assets.s3.amazonaws.com/Footer1-83/v1/images/Icon-twitter.png\" alt=\"Twitter\"></a>\r\n");
      out.write("      <a href=\"#\"><img class=\"link-img\" src=\"https://workik-widget-assets.s3.amazonaws.com/Footer1-83/v1/images/Icon-facebook.png\" alt=\"Facebook\"></a>\r\n");
      out.write("      <a href=\"#\"><img class=\"link-img\" src=\"https://workik-widget-assets.s3.amazonaws.com/Footer1-83/v1/images/Icon-google.png\" alt=\"Google\"></a>\r\n");
      out.write("      <a href=\"#\"><img class=\"link-img\" src=\"https://workik-widget-assets.s3.amazonaws.com/Footer1-83/v1/images/Icon-instagram.png\" alt=\"Instagram\"></a>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
